### ISSUE TITLE
Plugin-ize the DWIW vimscript?

### ISSUE THREAD

**Issue by chexxor** [mkropat/vim-dwiw2015#13]
I installed this project on Windows through Chocolatey, and I really liked the default settings.

I got a macbook for work, and I want to use the same settings. Currently, I've just copy-pasted the settings in your dwiw vimscript into my .vimrc, but I'd rather just add `Plugin 'mkropat/vim-dwiw'` or similar.

What do you think? Does it make sense to pull your base settings into a vim plugin on github?

**Comment by mkropat** [comment]
Cool. Yeah, I agree that it should be supported. It's been a while since I've tested it but what you're asking for [should already work](https://github.com/mkropat/vim-dwiw2015#plug-in-only) (if I'm understanding you correctly).

The line would look like:

     Plugin 'mkropat/vim-dwiw2015'

Then you can do `:PluginInstall`

**Comment by mkropat** [comment]
I should mention that under-the-hood, vim-dwiw2015 is actually just a Vim plugin, modeled after its inspiration, [vim-sensible](https://github.com/tpope/vim-sensible).

**Comment by chexxor** [comment]
OH! I didn't even notice that I could add this repo using Vundle like that.

I tried adding it to my Plugins list, but I got a few errors.

```
Error detected while processing /Users/aberg/.vim/bundle/vim-dwiw2015/plugin/dwiw2015.vim:
line  155:
E31: No such mapping
line  160:
E31: No such mapping
line  165:
E31: No such mapping
```

Thoughts?

155: unmap <C-V>
160: unmap <C-Y>
165: unmap <C-Z>

Should we just wrap those in an a condition check? Like, "if (!exists(map <C-V>))"?

**Comment by chexxor** [comment]
Note about above mapping errors - I was using MacVim to get those. I'm guessing MacVim customizes the default keybindings, which DWIW2015 wasn't expecting.

**Comment by mkropat** [comment]
Maybe. I test in MacVim and I haven't seen the issue before. Either way it's definitely a good fix, because clearly it happens in some circumstances.

**Comment by chexxor** [comment]
I don't think there's a reason to keep this open.
